# Generated by Django 4.1.6 on 2023-02-20 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='managed_by',
            field=models.ForeignKey(help_text='Expects a partner manager user profile to manage this Agency Profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='sub_agency_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='TM30 percentage for the service', max_digits=20, null=True),
        ),
    ]
