# Generated by Django 4.1.6 on 2023-02-21 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_transaction_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='managed_by',
            field=models.ForeignKey(blank=True, help_text='Expects a partner manager user profile to manage this Agency Profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
