# Generated by Django 4.1.6 on 2023-02-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_userdetail_business_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='business_email',
            field=models.EmailField(blank=True, help_text='For businesses', max_length=100, null=True, unique=True),
        ),
    ]
