# Generated by Django 4.1.6 on 2023-02-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_userdetail_business_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
