# Generated by Django 4.1.6 on 2023-02-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_userrole_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='user_type',
            field=models.CharField(blank=True, choices=[('platform', 'Platform'), ('agency', 'Agency'), ('individual', 'Individual'), ('developer', 'Developer'), ('corporate-business', 'Corporate-Business')], max_length=25, null=True),
        ),
    ]
