# Generated by Django 4.1.6 on 2023-03-05 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_alter_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='agency',
            field=models.ManyToManyField(help_text='If agencies can have more than 1 service.', to=settings.AUTH_USER_MODEL),
        ),
    ]
