# Generated by Django 4.1.6 on 2023-03-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_transaction_document_transaction_document_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='document',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='document_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
