# Generated by Django 4.1.6 on 2023-03-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_remove_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20, null=True),
        ),
    ]
