# Generated by Django 4.1.6 on 2023-03-10 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0050_remove_transaction_service_channel_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='service_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.service'),
        ),
    ]
