# Generated by Django 4.1.6 on 2023-03-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0054_remove_transaction_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='document',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='document_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
