# Generated by Django 4.1.6 on 2023-03-13 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0056_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='manages',
            field=models.ManyToManyField(blank=True, help_text='This field contains who this User Detail (Partner Manager) manages', related_name='manages', to=settings.AUTH_USER_MODEL),
        ),
    ]
