# Generated by Django 4.1.6 on 2023-03-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0059_rename_is_active_service_activate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=200, null=True),
        ),
    ]
