# Generated by Django 4.1.6 on 2023-03-17 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0061_alter_servicedetail_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='document',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='document_id',
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='logo',
            field=models.ImageField(default='default/user.jpg', null=True, upload_to='service/'),
        ),
    ]
