# Generated by Django 4.1.6 on 2023-03-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0062_remove_service_agency_remove_servicedetail_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='document',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='document_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
