# Generated by Django 4.1.6 on 2023-03-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0075_alter_service_logo_alter_servicedetail_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Tells if this service is available for use. i.e Services can be deactivated.'),
        ),
    ]
