# Generated by Django 4.1.6 on 2023-04-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0076_alter_servicedetail_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='name',
            field=models.CharField(blank=True, help_text='Agency, Sub-Agency, Business, Individual ... names', max_length=250, null=True),
        ),
    ]
