# Generated by Django 4.1.6 on 2023-04-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0079_alter_channel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'This email has already been registered.'}, max_length=200, null=True, unique=True),
        ),
    ]
