# Generated by Django 4.1.6 on 2023-04-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0081_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='email',
            field=models.EmailField(blank=True, error_messages={'invalid': 'this', 'unique': 'This email has already been registered.'}, max_length=200, null=True, unique=True),
        ),
    ]
