# Generated by Django 4.2 on 2023-04-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0085_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetail',
            name='added_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text="This is an extra amount added by a sub agency, this amount would be added to the 'price' (price + added_amount) field in this model, which reveals the total amount a subagency is offeriing the service to consumers", max_digits=200, null=True),
        ),
    ]
