# Generated by Django 4.1.6 on 2023-05-01 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0089_alter_user_otp_expire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_expire',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 1, 22, 24, 46, 326537)),
        ),
    ]
