# Generated by Django 4.1.6 on 2023-05-03 08:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0090_remove_user_otp_alter_user_otp_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Agency service used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Who made this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_expire',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 9, 43, 11, 889321)),
        ),
    ]
