# Generated by Django 4.1.6 on 2023-05-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0096_alter_transaction_document_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='verification_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
