# Generated by Django 4.1.6 on 2023-05-14 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0098_merge_20230514_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetail',
            name='parent_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.userdetail'),
        ),
    ]
