# Generated by Django 4.1.6 on 2023-05-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0100_servicedetail_domain_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='service_detail_code',
            field=models.CharField(blank=True, help_text='A unique identifier for this agency used for identifying what logic to be run when this service detail is selected.', max_length=20, null=True),
        ),
    ]
