# Generated by Django 4.1.6 on 2023-07-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0104_remove_paymentgateway_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payload',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='In percentage', max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_number',
            field=models.CharField(blank=True, help_text='VerifyPro Transaction Ref.', max_length=200, null=True),
        ),
    ]
