# Generated by Django 4.1.6 on 2023-07-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0106_alter_transaction_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpaymentgatewaydetail',
            name='select_sub_type',
            field=models.CharField(blank=True, choices=[('direct', 'Direct'), ('split', 'Split')], default='split', max_length=20, null=True, unique=True),
        ),
    ]
