# Generated by Django 4.1.6 on 2023-02-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userdetail_managed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='admin_type',
            field=models.CharField(choices=[('Super-Admin', 'super-admin'), ('Partner-Manager', 'partner-manager'), ('Sub-Agency', 'sub-agency'), ('Sub-Corporate-Business', 'sub-corporate-business')], default='super_admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='name',
            field=models.CharField(blank=True, choices=[('Platform', 'platform'), ('Agency', 'agency'), ('Individual', 'individual'), ('Corporate-Business', 'corporate-business')], max_length=30, null=True),
        ),
    ]
