# Generated by Django 4.1.6 on 2023-02-20 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_role_admin_type_alter_service_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(choices=[('Super-Admin', 'super-admin'), ('Partner-Manager', 'partner-manager'), ('Sub-Agency', 'sub-agency'), ('Sub-Corporate-Business', 'sub-corporate-business')], default='super-admin', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user_detail', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.userdetail')),
            ],
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
