# Generated by Django 4.1.6 on 2023-02-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userrole_delete_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='super_admin_has_reset_password',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
