# Generated by Django 4.1.6 on 2023-02-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_userdetail_activate_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_id',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('success', 'Success'), ('canceled', 'Canceled'), ('failed', 'Failed')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('success', 'Success'), ('canceled', 'Canceled'), ('failed', 'Failed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user_role',
            field=models.CharField(choices=[('super-admin', 'Super-Admin'), ('partner-manager', 'Partner-Manager'), ('sub-agency', 'Sub-Agency'), ('sub-corporate-business', 'Sub-Corporate-Business')], default='super-admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='name',
            field=models.CharField(blank=True, choices=[('platform', 'Platform'), ('agency', 'Agency'), ('individual', 'Individual'), ('corporate-business', 'Corporate-Business')], max_length=30, null=True),
        ),
    ]
