# Generated by Django 4.1.6 on 2023-02-22 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_userdetail_managed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='managed_by',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='managed_by',
            field=models.ManyToManyField(blank=True, help_text='Expects a partner manager user profile to manage this Agency Profile', null=True, related_name='managers', to=settings.AUTH_USER_MODEL),
        ),
    ]
