# Generated by Django 4.1.6 on 2023-02-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_userdetail_managed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='user_type',
            field=models.CharField(blank=True, choices=[('platform', 'Platform'), ('agency', 'Agency'), ('individual', 'Individual'), ('developer', 'Developer'), ('corporate-business', 'Corporate-Business')], max_length=30, null=True),
        ),
    ]
