# Generated by Django 4.1.6 on 2023-02-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_userdetail_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='channel_available',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
