# Generated by Django 4.1.6 on 2023-02-22 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_service_channel_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='business_type',
        ),
    ]
