# Generated by Django 4.1.6 on 2023-02-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_userdetail_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='user_role',
            field=models.CharField(choices=[('super-admin', 'Super-Admin'), ('partner-manager', 'Partner-Manager'), ('user', 'User'), ('sub-agency', 'Sub-Agency'), ('sub-corporate-business', 'Sub-Corporate-Business')], default='super-admin', max_length=100),
        ),
    ]
