# Generated by Django 4.1.6 on 2023-02-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_userrole_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='business_address',
            field=models.CharField(blank=True, help_text='For businesses', max_length=500, null=True),
        ),
    ]
