# Generated by Django 4.1.6 on 2023-02-27 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_alter_userrole_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='activate_business',
        ),
    ]
