# Generated by Django 4.1.6 on 2023-02-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_remove_userdetail_activate_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
    ]
