# Generated by Django 4.1.6 on 2023-03-01 07:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_alter_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='manages',
            field=models.ManyToManyField(blank=True, help_text='This field contains who this User Detail (Partner Manager) managers', related_name='manages', to=settings.AUTH_USER_MODEL),
        ),
    ]
