# Generated by Django 4.1.6 on 2023-03-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='business_address',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='address',
            field=models.CharField(blank=True, help_text='General Address', max_length=500, null=True),
        ),
    ]
