# Generated by Django 4.1.6 on 2023-03-04 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_remove_userdetail_business_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='state',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.state'),
        ),
    ]
