# Generated by Django 4.1.6 on 2023-03-04 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_userdetail_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.state'),
        ),
    ]
