# Generated by Django 4.1.6 on 2023-03-04 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_alter_userdetail_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Who created this Sub Agency', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='state',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.state'),
        ),
    ]
