# Generated by Django 4.1.6 on 2023-03-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_remove_servicedetail_agency_remove_service_agency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
