# Generated by Django 4.1.6 on 2023-03-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_alter_service_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='document',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='document_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
