# Generated by Django 4.1.6 on 2023-03-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0045_alter_userdetail_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='email',
            field=models.EmailField(blank=True, help_text="Agency's email", max_length=200, null=True, unique=True),
        ),
    ]
