# Generated by Django 4.1.6 on 2023-03-08 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_userdetail_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='document',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='document_id',
        ),
    ]
