# Generated by Django 4.1.6 on 2023-03-10 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_transaction_document_transaction_document_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='service',
        ),
        migrations.AddField(
            model_name='channel',
            name='logo',
            field=models.ImageField(default='default/user.jpg', null=True, upload_to='channels/'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='service_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.servicedetail'),
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='channel_available',
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.service'),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='channel_available',
            field=models.ManyToManyField(blank=True, to='account.channel'),
        ),
    ]
