# Generated by Django 4.1.6 on 2023-03-10 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0052_remove_transaction_service_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetail',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='service_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.servicedetail'),
        ),
    ]
