# Generated by Django 4.1.6 on 2023-03-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0053_servicedetail_name_transaction_service_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='document',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='document_id',
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='document',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('free', 'Free')], default='paid', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='document_id',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('free', 'Free')], default='paid', max_length=50, null=True),
        ),
    ]
