# Generated by Django 4.1.6 on 2023-03-17 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0060_alter_servicedetail_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.service'),
        ),
    ]
