# Generated by Django 4.1.6 on 2023-03-19 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0065_service_logo_alter_servicedetail_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
