# Generated by Django 4.1.6 on 2023-03-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0066_alter_service_name_alter_servicedetail_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetail',
            name='service_detail_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
