# Generated by Django 4.1.6 on 2023-03-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0071_remove_servicedetail_service_detail_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_code',
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='service_detail_code',
            field=models.CharField(blank=True, help_text='A unique identifier for this agency used for identifying what logic to be run when this service detail is selected.', max_length=20, null=True),
        ),
    ]
