# Generated by Django 4.1.6 on 2023-03-24 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0072_remove_service_service_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='is_available',
            field=models.BooleanField(default=False, help_text='Tells if this service is available for use. i.e Services can be deactivated.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Agency service used.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency', to=settings.AUTH_USER_MODEL),
        ),
    ]
