# Generated by Django 4.1.6 on 2023-03-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0074_alter_servicedetail_service_detail_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='logo',
            field=models.ImageField(default='default/user.jpg', null=True, upload_to='service/'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='logo',
            field=models.ImageField(default='default/user.jpg', null=True, upload_to='service/'),
        ),
    ]
