# Generated by Django 4.1.6 on 2023-04-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0077_alter_userdetail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='name',
            field=models.CharField(blank=True, help_text='Agency, Sub-Agency, Business, Individual ... names', max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='user_type',
            field=models.CharField(blank=True, choices=[('platform', 'Platform'), ('agency', 'Agency'), ('individual', 'Individual'), ('developer', 'Developer'), ('corporate-business', 'Corporate-Business')], max_length=35, null=True),
        ),
    ]
