# Generated by Django 4.1.6 on 2023-04-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0083_alter_userdetail_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='push_notification',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
