# Generated by Django 4.1.6 on 2023-05-01 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0088_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_expire',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 1, 21, 47, 6, 589014)),
        ),
    ]
