# Generated by Django 4.1.6 on 2023-05-03 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0091_alter_transaction_agency_alter_transaction_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_expire',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
