# Generated by Django 4.1.6 on 2023-05-07 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0092_alter_user_otp_expire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_expire',
        ),
    ]
