# Generated by Django 4.1.6 on 2023-05-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0092_alter_user_otp_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
