# Generated by Django 4.1.6 on 2023-05-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0095_alter_transaction_payment_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='document_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
