# Generated by Django 4.1.6 on 2023-05-14 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0094_user_otp_expire'),
        ('account', '0097_transaction_verification_number'),
    ]

    operations = [
    ]
