# Generated by Django 4.1.6 on 2023-05-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0101_alter_servicedetail_service_detail_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
