# Generated by Django 4.1.6 on 2023-07-12 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0103_rename_name_transaction_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentgateway',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='name',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='updated_on',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_gateway',
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='payment_gateway_logo',
            field=models.ImageField(default='default/cash.png', null=True, upload_to='payments/'),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='payment_gateway_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='payment_gateway_slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='payment_gateway_type',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='added_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text="This is an extra amount added by a sub agency, this amount would be added to the 'price' (price + added_amount) field in this model, which reveals the total amount a sub-agency is offering the service to consumers", max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Transaction Ref.', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ClientPaymentGateWayDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_gateway_is_active', models.BooleanField(default=False)),
                ('secret_key', models.CharField(blank=True, help_text="Used to authenticate request and should be kept secret. Can also store TMSASS 'client_id'", max_length=500, null=True)),
                ('settlement_account', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('bank_code', models.CharField(blank=True, help_text='UBA = 033', max_length=200, null=True, unique=True)),
                ('bank_name', models.CharField(blank=True, help_text='UBA', max_length=200, null=True, unique=True)),
                ('account_code', models.CharField(blank=True, help_text='A token used for making payment to the account number attached to this model. Mostly used for TMSASS', max_length=200, null=True, unique=True)),
                ('offline_bank_account_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('offline_bank_account_owner_name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('offline_bank_name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('payment_gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.paymentgateway')),
                ('user_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.userdetail')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.clientpaymentgatewaydetail'),
        ),
    ]
