# Generated by Django 4.1.6 on 2023-07-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0105_transaction_payload_alter_servicedetail_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payload',
            field=models.JSONField(default=dict),
        ),
    ]
